name: Deploy to Pages

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install packages
      run: pnpm i --shamefully-hoist

    - name: Build
      working-directory: ./packages/docs
      run: pnpm build
      env:
        PUBLIC_PATH: /vue-create-ripple-docs/

    - name: Init git repo and push it to master:gh-pages
      working-directory: ./packages/docs/dist
      run: |
        git config --global user.email "${GITHUB_ACTOR}@https://users.noreply.github.com/"
        git config --global user.name "${GITHUB_ACTOR}"
        git init
        git add --all
        git commit -m "Auto update pages on $(date +'%Y-%m-%d %H:%M:%S')"
        git push -f https://${{ secrets.MY_GITHUB_ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git master:gh-pages
