on:
  push:
    branches: [ develop ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install packages
        run: pnpm install --shamefully-hoist

      - name: Test & Build
        working-directory: ./packages/vue-create-ripple
        run: pnpm test:unit && pnpm build

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./packages/vue-create-ripple/package.json
          dry-run: true