on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install packages
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Unit tests
        run: npm run test:unit

      - name: Build
        run: npm run build

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}